plugins {
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT'
    id 'com.modrinth.minotaur' version '2.+'
}

group = "team.creative"

repositories {
    maven {
        url = "https://api.modrinth.com/maven"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "maven.modrinth:modmenu:${project.modmenu_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	
    implementation project(path: ':CreativeCore')
}

modDependencies = [
    creativecore: ">=" + creativecore_version
]
modSides=[ "client" ]
